name: Backend CI/CD

on:
  push:
    branches:
      - CICD

env:
  PROJECT_NAME: Summer2025SWD392_NET1703_Group2_BE
  DOTNET_VERSION: 8.0.x
  EC2_HOST: ${{ secrets.EC2_HOST_PUBLIC }}
  EC2_USER: ${{ secrets.EC2_USER }}
  SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

jobs:
  build:
    name: Build ASP.NET Core
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Create zip artifact
        run: zip -r publish.zip ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-publish
          path: publish.zip

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-publish

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

      - name: Upload to EC2
        run: |
          scp publish.zip ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/
          ssh ${EC2_USER}@${EC2_HOST} "
            rm -rf ~/deploy_temp &&
            mkdir -p ~/deploy_temp &&
            unzip -o publish.zip -d ~/deploy_temp &&
            sudo systemctl stop kestrel-${{ env.PROJECT_NAME }}.service &&
            sudo cp -r ~/deploy_temp/* /var/www/${{ env.PROJECT_NAME }}/ &&
            sudo systemctl start kestrel-${{ env.PROJECT_NAME }}.service
          "
